seed: 42
run_dir: runs/icfie_yolo-5-13-a1-b1-c1
hyp_path: yolov7/data/hyp.scratch.p5.yaml
project_after_fusion: true
normalize_png_before_train: true
save_every: 1
use_ota_loss: false
cache_images: false
rect: false
dataset:
  train_path: /home/pushk3n/github-ai2/data/Exdark/train.txt
  val_path: /home/pushk3n/github-ai2/data/Exdark/val.txt
  num_classes: 12
  class_names:
  - Bicycle
  - Boat
  - Bottle
  - Bus
  - Car
  - Cat
  - Chair
  - Cup
  - Dog
  - Motorbike
  - People
  - Table
  image_size: 416
  single_cls: false
nc: 12
names:
- Bicycle
- Boat
- Bottle
- Bus
- Car
- Cat
- Chair
- Cup
- Dog
- Motorbike
- People
- Table
yolo:
  cfg_path: yolov7/cfg/training/yolov7.yaml
  weights_path: yolov7/yolov7.pt
  num_classes: 12
hardware:
  device: cuda:0
  use_amp: true
  batch_size: 4
  accumulate_steps: 4
  num_workers: 4
  pin_memory: true
  ddp: false
  use_grad_checkpoint: true
optimizer:
  stage_a_lr: 0.0001
  lr: 0.01
  stage_c_lr: 0.0001
  min_lr: 1.0e-05
  weight_decay: 0.0005
  beta1: 0.937
  beta2: 0.999
schedule:
  stage_a_epochs: 1
  stage_b_epochs: 1
  stage_c_epochs: 1
visualization:
  batch_log_interval: 25
